trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Compile vscode-test"
    corepack enable
    pnpm install
    pnpm compile
    echo ">>> Compiled vscode-test"
    cd sample
    echo ">>> Run sample integration test"
    pnpm install
    pnpm compile
    pnpm test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Install @vscode/vsce"
    pnpm add -D @vscode/vsce
    echo ">>> Publish"
    pnpm deploy -p $(VSCODE_MARKETPLACE_TOKEN)
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), not(contains(variables['Build.SourceBranch'], '-')), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Install @vscode/vsce"
    pnpm add -D @vscode/vsce
    echo ">>> Publish pre-release"
    pnpm deploy-prerelease -p $(VSCODE_MARKETPLACE_TOKEN)
  displayName: Publish pre-release
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), contains(variables['Build.SourceBranch'], '-'), eq(variables['Agent.OS'], 'Linux'))
